Add tag latest option

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -66,10 +66,10 @@ jobs:
         with:
           prefix: 'v'
 
-      - name: Check if tag format is valid
+      - name: Exit on invalid tag format
         if: startsWith(github.ref, 'refs/tags/') && steps.check-tag-format.outputs.is_valid == 'false'
         run: |
-          echo "Invalid tag format, it must follow SemVer. Aborting." && exit 1
+          echo "Tag must follow SemVer convention. Aborting." && exit 1
 
       - name: Get release type
         if: startsWith(github.ref, 'refs/tags/')
@@ -80,8 +80,13 @@ jobs:
             const regex = /(alpha|beta)/
             const refName = context.ref.replace('refs/tags/', '')
             console.log(`Ref name: ${refName}`)
-            const releaseType = (refName.match(regex))[0]
-            console.log(`Release type: ${releaseType}`)
+            const releaseTypeMatch = refName.match(regex)
+            if (!releaseTypeMatch) {
+              releaseType = 'latest'
+            } else {
+              releaseType =  refName.match(regex)[0]
+            }
+            console.log(`Release type: ${releaseType}`);
             return releaseType
 
       # - name: Publish release
