Add tag validations

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,6 +28,10 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      ###
+      # Build
+      ###
+
       # - name: Set up Node.js ${{ matrix.node-version }}
       #   uses: actions/setup-node@v4
       #   with:
@@ -50,6 +54,22 @@ jobs:
 
       # - name: Test
       #   run: yarn test
+
+      ###
+      # Release
+      ###
+
+      - name: Check tag format
+        id: check-tag-format
+        if: startsWith(github.ref, 'refs/tags/')
+        uses: nowsprinting/check-version-format-action@v4
+        with:
+          prefix: 'v'
+
+      - name: Check if tag format is valid
+        if: startsWith(github.ref, 'refs/tags/') && steps.check-tag-format.outputs.is_valid == 'false'
+        run: |
+          echo "Invalid tag format, it must follow SemVer. Aborting." && exit 1
 
       - name: Get release type
         if: startsWith(github.ref, 'refs/tags/')
